version: '3'

networks:
  cps_sim:
    driver: bridge
    ipam:
     config:
       - subnet: 172.21.0.0/24

services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    networks:
      cps_sim:
        #        ipv4_address: 172.21.0.2

  controller:
    build: ./elevatorcontroller
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/controller
    depends_on:
      - mqtt
    environment:
      - mqtt_host=mqtt
    networks:
      cps_sim:
        #ipv4_address: 172.21.0.3

  telegraf:
    image: telegraf:latest
    volumes:
      - ./gui/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    networks:
      cps_sim:

  influxdb:
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
    depends_on:
      - mqtt
    volumes:
    # Data persistency
    - ./gui/influxdb/data:/var/lib/influxdb
    networks:
      cps_sim:

  grafana:
    image: grafana/grafana:latest
    user: "0"
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    depends_on:
      - influxdb
    volumes:
    # Data persistency
      - ./gui/grafana/data:/var/lib/grafana
    networks:
      cps_sim:
  elevator1:
    container_name: elevator1
    build: ./elevator
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/elevator
    environment:
      - capacity=20
      - mqtt_host=mqtt
      - elevator_id=1
    depends_on:
      - mqtt
      - controller
    networks:
      cps_sim:

  floor0:
    container_name: floor0
    build: ./floor
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
      - floor_level=0
    depends_on:
      - mqtt
      - controller
    networks:
      cps_sim:

  floor1:
    container_name: floor1
    build: ./floor
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
      - floor_level=1
    depends_on:
      - mqtt
      - controller
    networks:
      cps_sim:

  floor2:
    container_name: floor2
    build: ./floor
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
    depends_on:
      - mqtt
      - controller
    networks:
      cps_sim:

  floor3:
    container_name: floor3
    build: ./floor
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
    depends_on:
      - mqtt
      - controller
    networks:
      cps_sim:

  floor4:
    container_name: floor4
    build: ./floor
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
    depends_on:
      - mqtt
      - controller
    networks:
      cps_sim:

