version: '3'

networks:
  cps_sim:
    driver: bridge
    ipam:
     config:
       - subnet: 172.21.0.0/24

services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    networks:
      cps_sim:
        ipv4_address: 172.21.0.2

  controller:
    build: ./elevatorcontroller
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/controller
    depends_on:
      - mqtt
    environment:
      - mqtt_host=mqtt
    networks:
      cps_sim:
        ipv4_address: 172.21.0.3

  input_feeder:
    build: ./input-feeder
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/input-feeder
    depends_on:
      - mqtt
    environment:
      - mqtt_host=mqtt
    networks:
      cps_sim:
        ipv4_address: 172.21.0.4

  elevator1:
    container_name: elevator1
    build: ./elevator
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/elevator
    environment:
      - capacity=20
      - mqtt_host=mqtt
      - elevator_id=1
    depends_on:
      - mqtt
      - controller
    networks:
      cps_sim:
        ipv4_address: 172.21.0.5

  floor0:
    container_name: floor0
    build: ./floor
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
    depends_on:
      - mqtt
      - controller
      - input_feeder
    networks:
      cps_sim:
        ipv4_address: 172.21.0.6

  floor1:
    container_name: floor1
    build: ./floor
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
    depends_on:
      - mqtt
      - controller
      - input_feeder
    networks:
      cps_sim:
        ipv4_address: 172.21.0.7

  floor2:
    container_name: floor2
    build: ./floor
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
    depends_on:
      - mqtt
      - controller
      - input_feeder
    networks:
      cps_sim:
        ipv4_address: 172.21.0.8

  floor3:
    container_name: floor3
    build: ./floor
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
    depends_on:
      - mqtt
      - controller
      - input_feeder
    networks:
      cps_sim:
        ipv4_address: 172.21.0.9

  floor4:
    container_name: floor4
    build: ./floor
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
    depends_on:
      - mqtt
      - controller
      - input_feeder
    networks:
      cps_sim:
        ipv4_address: 172.21.0.10

