version: '3'
services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"

  elevator1:
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/elevator
    environment:
      - capacity=20
      - mqtt_host=mqtt
    depends_on:
      - mqtt

  elevator2:
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/elevator
    environment:
      - capacity=20
      - mqtt_host=mqtt
    depends_on:
      - mqtt

  elevator3:
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/elevator
    environment:
      - capacity=20
      - mqtt_host=mqtt
    depends_on:
      - mqtt

  elevator4:
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/elevator
    environment:
      - capacity=20
      - mqtt_host=mqtt
    depends_on:
      - mqtt

  elevator5:
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/elevator
    environment:
      - capacity=20
      - mqtt_host=mqtt
    depends_on:
      - mqtt

  elevator6:
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/elevator
    environment:
      - capacity=20
      - mqtt_host=mqtt
    depends_on:
      - mqtt

  floor1:
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/FahrgastSimulator
    environment:
      - camera_floor=1
      - mqtt_host=mqtt
    depends_on:
      - mqtt

  floor2:
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/FahrgastSimulator
    environment:
      - camera_floor=2
      - mqtt_host=mqtt
    depends_on:
      - mqtt

  floor3:
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/FahrgastSimulator
    environment:
      - camera_floor=3
      - mqtt_host=mqtt
    depends_on:
      - mqtt

  floor4:
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/FahrgastSimulator
    environment:
      - camera_floor=4
      - mqtt_host=mqtt
    depends_on:
      - mqtt

  floor5:
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/FahrgastSimulator
    environment:
      - camera_floor=5
      - mqtt_host=mqtt
    depends_on:
      - mqtt

  floor6:
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/FahrgastSimulator
    environment:
      - camera_floor=6
      - mqtt_host=mqtt
    depends_on:
      - mqtt

  floor7:
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/FahrgastSimulator
    environment:
      - camera_floor=7
      - mqtt_host=mqtt
    depends_on:
      - mqtt

  floor8:
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/FahrgastSimulator
    environment:
      - camera_floor=8
      - mqtt_host=mqtt
    depends_on:
      - mqtt

  floor9:
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/FahrgastSimulator
    environment:
      - camera_floor=9
      - mqtt_host=mqtt
    depends_on:
      - mqtt

  floor10:
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/FahrgastSimulator
    environment:
      - camera_floor=10
      - mqtt_host=mqtt
    depends_on:
      - mqtt

  floor11:
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/FahrgastSimulator
    environment:
      - camera_floor=11
      - mqtt_host=mqtt
    depends_on:
      - mqtt

