version: "3"
volumes:
  cps_data:
services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"

  recorder:
    container_name: recorder
    build:
      context: ./
      dockerfile: ./recorder/Dockerfile
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/recorder
    depends_on:
      - mqtt
    environment:
      - mqtt_host=mqtt
      - log_level=DEBUG
      - resdir=/app/recorder/data
    volumes:
      - cps_data:/app/recorder/data

  controller:
    build:
      context: ./
      dockerfile: ./controller/Dockerfile
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/controller
    restart: always
    depends_on:
      - mqtt
    environment:
      - mqtt_host=mqtt
      - floor_count=10
      - elevator_count=6
      - log_level=DEBUG
      - mode=smart

  elevator0:
    container_name: elevator0
    build:
      context: ./
      dockerfile: ./elevator/Dockerfile
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/elevator
    restart: always
    environment:
      - capacity=10
      - mqtt_host=mqtt
      - elevator_id=0
      - log_level=DEBUG
    depends_on:
      - mqtt
      - controller

  elevator1:
    container_name: elevator1
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/elevator
    restart: always
    environment:
      - capacity=10
      - mqtt_host=mqtt
      - elevator_id=1
      - log_level=DEBUG
    depends_on:
      - mqtt
      - controller

  elevator2:
    container_name: elevator2
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/elevator
    restart: always
    environment:
      - capacity=10
      - mqtt_host=mqtt
      - elevator_id=2
      - log_level=DEBUG
    depends_on:
      - mqtt
      - controller

  elevator3:
    container_name: elevator3
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/elevator
    restart: always
    environment:
      - capacity=10
      - mqtt_host=mqtt
      - elevator_id=3
      - log_level=DEBUG
    depends_on:
      - mqtt
      - controller

  elevator4:
    container_name: elevator4
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/elevator
    restart: always
    environment:
      - capacity=10
      - mqtt_host=mqtt
      - elevator_id=4
      - log_level=DEBUG
    depends_on:
      - mqtt
      - controller

  elevator5:
    container_name: elevator5
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/elevator
    restart: always
    environment:
      - capacity=10
      - mqtt_host=mqtt
      - elevator_id=5
      - log_level=DEBUG
    depends_on:
      - mqtt
      - controller

  floor0:
    container_name: floor0
    build:
      context: ./
      dockerfile: ./floor/Dockerfile
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
      - floor_id=0
      - log_level=DEBUG
    depends_on:
      - mqtt
      - controller

  floor1:
    container_name: floor1
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
      - floor_id=1
      - log_level=DEBUG
    depends_on:
      - mqtt
      - controller

  floor2:
    container_name: floor2
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
      - floor_id=2
      - log_level=DEBUG
    depends_on:
      - mqtt
      - controller

  floor3:
    container_name: floor3
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
      - floor_id=3
      - log_level=DEBUG
    depends_on:
      - mqtt
      - controller

  floor4:
    container_name: floor4
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
      - floor_id=4
      - log_level=DEBUG
    depends_on:
      - mqtt
      - controller

  floor5:
    container_name: floor5
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
      - floor_id=5
      - log_level=DEBUG
    depends_on:
      - mqtt
      - controller

  floor6:
    container_name: floor6
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
      - floor_id=6
      - log_level=DEBUG
    depends_on:
      - mqtt
      - controller

  floor7:
    container_name: floor7
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
      - floor_id=7
      - log_level=DEBUG
    depends_on:
      - mqtt
      - controller

  floor8:
    container_name: floor8
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
      - floor_id=8
      - log_level=DEBUG
    depends_on:
      - mqtt
      - controller

  floor9:
    container_name: floor9
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
      - floor_id=9
      - log_level=DEBUG
    depends_on:
      - mqtt
      - controller
