version: '3'
services:
  # telegraf:
  #   image: telegraf:latest
  #   volumes:
  #     - ./gui/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  #   depends_on:
  #     - influxdb

  # influxdb:
  #   image: influxdb:latest
  #   ports:
  #     - "8083:8083"
  #     - "8086:8086"
  #     - "8090:8090"
  #   environment:
  #     - INFLUXDB_DATA_ENGINE=tsm1
  #     - INFLUXDB_REPORTING_DISABLED=false
  #   depends_on:
  #     - mqtt
  #   volumes:
  #   # Data persistency
  #   - ./gui/influxdb/data:/var/lib/influxdb

  # grafana:
  #   image: grafana/grafana:latest
  #   user: "0"
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
  #   depends_on:
  #     - influxdb
  #   volumes:
  #   # Data persistency
  #     - ./gui/grafana/data:/var/lib/grafana

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"

  controller:
      build: ./elevatorcontroller
      image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/controller
      restart: always
      depends_on:
        - mqtt
      environment:
        - mqtt_host=mqtt
        - floor_count=4
        - elevator_count=1

  elevator0:
    container_name: elevator0
    build: ./elevator
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/elevator
    restart: always
    environment:
      - capacity=10
      - mqtt_host=mqtt
      - elevator_id=0
    depends_on:
      - mqtt
      - controller

  floor0:
    container_name: floor0
    build: ./floor
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
      - floor_level=0
    depends_on:
      - mqtt
      - controller

  floor1:
    container_name: floor1
    build: ./floor
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
      - floor_level=1
    depends_on:
      - mqtt
      - controller

  floor2:
    container_name: floor2
    build: ./floor
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
      - floor_level=2
    depends_on:
      - mqtt
      - controller

  floor3:
    container_name: floor3
    build: ./floor
    image: docker-hub.informatik.haw-hamburg.de/wp-cps/simulation/floor
    environment:
      - mqtt_host=mqtt
      - floor_level=3
    depends_on:
      - mqtt
      - controller

